site_name: Ehco-Relay Docs
site_url: https://docs.ehco-relay.cc
theme:
  name: material
  palette:
    - scheme: default
      primary: white
      toggle:
        icon: material/brightness-7
        name: Dark mode
    - scheme: slate
      primary: custom
      toggle:
        icon: material/brightness-4
        name: Light mode

  logo: assets/logo.svg
  favicon: assets/fav.png
  icon:
    repo: fontawesome/brands/github

  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - content.code.copy
    - content.code.annotate
    - announce.dismiss
    - search.suggest
    - search.highlight

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Ehco1996/ehco
    - icon: fontawesome/brands/twitter
      link: https://x.com/Ehco1996
    - icon: fontawesome/brands/telegram
      link: https://t.me/Ehco1996

extra_css:
  - stylesheets/extra.css

nav:
  - 首页: index.md
  - 流量转发是什么？: intro.md
  - 使用文档:
      - 转发规则:
          - 直接转发: rule/direct.md
          - 隧道转发: rule/tunnel.md
      - 节点托管:
          - 1. 配置: node/manage.md
          - 2. 部署: node/install.md
      - 使用场景:
          - 流量转发: usage/relay.md
          - 内网穿透: usage/intranet.md
          - 性能监控: usage/monitor.md
  - FAQ: faq.md
  - 中转服务: https://ehco-relay.cc
  - 内核源码: https://github.com/Ehco1996/ehco
